/* =========================================================================
 * 规则编号: R0001
 * 规则名称: 用户行为宽表三场景 UNION ALL 加工
 * 目标表:   dwb_user_behavior_f
 * 设计意图:
 *   将三类互斥的用户行为事件流（电商交易 / 内容互动 / 社交关系）按统一的
 *   用户 + 行为 + 领域扩展 字段模型 UNION ALL 合并到一张行为宽表。
 *   因 user_* 与通用行为字段在三场景物理上同属每一行，无法分配到多条场景规则，
 *   故用单条 SELECT 承载全部 184 个目标字段（含 4 审计字段），三场景作为
 *   并联 JOIN 子图在同一 SQL 内并行产出，最终 UNION ALL。
 * 三场景说明:
 *   场景1 电商交易: 主表 ods.ods_order_main_f(oom)
 *                   + dim.dim_product_d(dpd, oom.product_id=dpd.product_id)
 *                   + dim.dim_user_base_d(dub, oom.user_id=dub.user_id)
 *                   → order_*/prod_* 取真值, 其余领域字段 NULL
 *   场景2 内容互动: 主表 ods.ods_content_interaction_f(oci)
 *                   + dim.dim_content_d(dcd, oci.content_id=dcd.content_id)
 *                   + dim.dim_user_base_d(dub7, oci.user_id=dub7.user_id)
 *                   → content_* 取真值, 其余领域字段 NULL
 *   场景3 社交关系: 主表 ods.ods_social_relation_f(osr)
 *                   + dim.dim_user_profile_d(dup, osr.user_id=dup.user_id)
 *                   + dim.dim_user_base_d(dub10, osr.user_id=dub10.user_id)
 *                   → social_*/profile_* 取真值, 其余领域字段 NULL
 * 通用字段:
 *   user_* (30个) — 三场景分别取各自 JOIN 的 dub/dub7/dub10
 *   behavior_time/日期/时间派生 — S1/S3 用 create_time, S2 用 interaction_time
 * 粒度: 无变化（行级追加，无聚合无展开）
 * ========================================================================= */

-- =======================================================
-- 场景1: 电商交易 (oom + dpd + dub)
-- =======================================================
SELECT
  -- ========== user_* (30) ==========
  dub.user_id                                                            AS user_user_id,
  COALESCE(dub.user_name, '')                                            AS user_user_name,
  CONCAT(LEFT(COALESCE(dub.user_phone, ''), 3), '****',
         RIGHT(COALESCE(dub.user_phone, ''), 4))                         AS user_user_phone,
  CASE dub.gender WHEN 'M' THEN '男' WHEN 'F' THEN '女'
       ELSE '未知' END                                                   AS user_gender,
  CAST(EXTRACT(YEAR FROM CURRENT_DATE) AS INTEGER)
    - CAST(EXTRACT(YEAR FROM dub.birthday) AS INTEGER)                   AS user_age,
  dub.birthday                                                           AS user_birthday,
  COALESCE(dub.province_name, '')                                        AS user_province_name,
  COALESCE(dub.city_name, '')                                            AS user_city_name,
  COALESCE(dub.user_level, 0)                                            AS user_user_level,
  COALESCE(dub.user_level_name, '')                                      AS user_user_level_name,
  COALESCE(dub.vip_status, 0)                                            AS user_vip_status,
  dub.register_time                                                      AS user_register_time,
  CAST(dub.register_time AS DATE)                                        AS user_register_date,
  COALESCE(dub.user_status, '')                                          AS user_user_status,
  CASE dub.user_status WHEN 'ACTIVE' THEN '正常' WHEN 'INACTIVE' THEN '未激活'
       WHEN 'BANNED' THEN '封禁' ELSE '未知' END                         AS user_user_status_name,
  COALESCE(dub.source_channel, '')                                       AS user_source_channel,
  COALESCE(dub.source_type, '')                                          AS user_source_type,
  dub.first_active_time                                                  AS user_first_active_time,
  dub.last_active_time                                                   AS user_last_active_time,
  COALESCE(dub.active_days, 0)                                           AS user_active_days,
  COALESCE(dub.total_score, 0)                                           AS user_total_score,
  COALESCE(dub.credit_score, 0)                                          AS user_credit_score,
  COALESCE(dub.risk_level, '')                                           AS user_risk_level,
  COALESCE(dub.device_type, '')                                          AS user_device_type,
  COALESCE(dub.os_type, '')                                              AS user_os_type,
  COALESCE(dub.app_version, '')                                          AS user_app_version,
  COALESCE(dub.ip_address, '')                                           AS user_ip_address,
  COALESCE(dub.network_type, '')                                         AS user_network_type,
  COALESCE(dub.is_real_name, 0)                                          AS user_is_real_name,
  COALESCE(dub.verify_status, '')                                        AS user_verify_status,
  -- ========== behavior_* (10) ==========
  CAST(NULL AS BIGINT)                                                   AS behavior_id,
  oom.create_time                                                        AS behavior_time,
  CAST(oom.create_time AS DATE)                                          AS behavior_date,
  CAST(EXTRACT(HOUR FROM oom.create_time) AS INTEGER)                    AS behavior_hour,
  CAST(EXTRACT(DOW FROM oom.create_time) + 1 AS INTEGER)                 AS behavior_weekday,
  CAST(EXTRACT(MONTH FROM oom.create_time) AS INTEGER)                   AS behavior_month,
  CAST(EXTRACT(QUARTER FROM oom.create_time) AS INTEGER)                 AS behavior_quarter,
  CAST(EXTRACT(YEAR FROM oom.create_time) AS INTEGER)                    AS behavior_year,
  CASE WHEN EXTRACT(DOW FROM oom.create_time) IN (0, 6) THEN 1 ELSE 0 END AS is_weekend,
  CASE WHEN EXTRACT(HOUR FROM oom.create_time) BETWEEN 0 AND 5 THEN '凌晨'
       WHEN EXTRACT(HOUR FROM oom.create_time) BETWEEN 6 AND 11 THEN '上午'
       WHEN EXTRACT(HOUR FROM oom.create_time) BETWEEN 12 AND 13 THEN '中午'
       WHEN EXTRACT(HOUR FROM oom.create_time) BETWEEN 14 AND 17 THEN '下午'
       ELSE '晚上' END                                                   AS time_period,
  -- ========== order_* (30) ==========
  oom.order_id                                                           AS order_order_id,
  oom.order_no                                                           AS order_order_no,
  oom.order_status                                                       AS order_order_status,
  CASE oom.order_status WHEN 'PENDING' THEN '待支付' WHEN 'PAID' THEN '已支付'
       WHEN 'SHIPPED' THEN '已发货' WHEN 'COMPLETED' THEN '已完成'
       WHEN 'CANCELLED' THEN '已取消' ELSE '未知' END                    AS order_order_status_name,
  oom.order_amount                                                       AS order_order_amount,
  oom.discount_amount                                                    AS order_discount_amount,
  oom.actual_amount                                                      AS order_actual_amount,
  oom.payment_method                                                     AS order_payment_method,
  oom.payment_time                                                       AS order_payment_time,
  oom.shipping_fee                                                       AS order_shipping_fee,
  oom.product_count                                                      AS order_product_count,
  oom.sku_count                                                          AS order_sku_count,
  oom.is_first_order                                                     AS order_is_first_order,
  oom.coupon_id                                                          AS order_coupon_id,
  oom.coupon_name                                                        AS order_coupon_name,
  oom.points_used                                                        AS order_points_used,
  oom.points_earned                                                      AS order_points_earned,
  oom.complete_time                                                      AS order_complete_time,
  oom.cancel_time                                                        AS order_cancel_time,
  oom.cancel_reason                                                      AS order_cancel_reason,
  oom.merchant_id                                                        AS order_merchant_id,
  oom.merchant_name                                                      AS order_merchant_name,
  oom.delivery_type                                                      AS order_delivery_type,
  oom.delivery_time                                                      AS order_delivery_time,
  oom.receive_time                                                       AS order_receive_time,
  oom.receive_status                                                     AS order_receive_status,
  oom.order_source                                                       AS order_order_source,
  oom.remark                                                             AS order_remark,
  oom.invoice_type                                                       AS order_invoice_type,
  oom.invoice_title                                                      AS order_invoice_title,
  -- ========== prod_* (20) ==========
  dpd.product_id                                                         AS prod_product_id,
  COALESCE(dpd.product_name, '')                                         AS prod_product_name,
  COALESCE(dpd.product_code, '')                                         AS prod_product_code,
  dpd.sku_id                                                             AS prod_sku_id,
  COALESCE(dpd.sku_name, '')                                             AS prod_sku_name,
  COALESCE(dpd.brand_id, 0)                                              AS prod_brand_id,
  COALESCE(dpd.brand_name, '')                                           AS prod_brand_name,
  COALESCE(dpd.category_id, 0)                                           AS prod_category_id,
  COALESCE(dpd.category_name, '')                                        AS prod_category_name,
  COALESCE(dpd.category_level1, '')                                      AS prod_category_level1,
  COALESCE(dpd.category_level2, '')                                      AS prod_category_level2,
  COALESCE(dpd.category_level3, '')                                      AS prod_category_level3,
  COALESCE(dpd.price, 0)                                                 AS prod_price,
  COALESCE(dpd.cost_price, 0)                                            AS prod_cost_price,
  CASE WHEN dpd.price > 0 THEN (dpd.price - dpd.cost_price) / dpd.price * 100
       ELSE 0 END                                                        AS prod_profit_rate,
  COALESCE(dpd.stock_status, '')                                         AS prod_stock_status,
  COALESCE(dpd.sale_status, '')                                          AS prod_sale_status,
  COALESCE(dpd.product_type, '')                                         AS prod_product_type,
  COALESCE(dpd.is_virtual, 0)                                            AS prod_is_virtual,
  COALESCE(dpd.supplier_id, 0)                                           AS prod_supplier_id,
  -- ========== content_* (50) — 场景1 不适用 ==========
  CAST(NULL AS BIGINT)                                                   AS content_interaction_id,
  CAST(NULL AS BIGINT)                                                   AS content_content_id,
  CAST(NULL AS VARCHAR(50))                                              AS content_interaction_type,
  CAST(NULL AS VARCHAR(50))                                              AS content_interaction_type_name,
  CAST(NULL AS INTEGER)                                                  AS content_duration_seconds,
  CAST(NULL AS NUMERIC(5,2))                                             AS content_duration_minutes,
  CAST(NULL AS VARCHAR(1000))                                            AS content_comment_content,
  CAST(NULL AS INTEGER)                                                  AS content_comment_word_count,
  CAST(NULL AS VARCHAR(50))                                              AS content_share_platform,
  CAST(NULL AS INTEGER)                                                  AS content_share_count,
  CAST(NULL AS INTEGER)                                                  AS content_like_count,
  CAST(NULL AS INTEGER)                                                  AS content_comment_count,
  CAST(NULL AS INTEGER)                                                  AS content_collect_count,
  CAST(NULL AS INTEGER)                                                  AS content_forward_count,
  CAST(NULL AS INTEGER)                                                  AS content_is_original,
  CAST(NULL AS VARCHAR(50))                                              AS content_source_type,
  CAST(NULL AS INTEGER)                                                  AS content_browse_depth,
  CAST(NULL AS NUMERIC(5,2))                                             AS content_scroll_percentage,
  CAST(NULL AS INTEGER)                                                  AS content_click_count,
  CAST(NULL AS INTEGER)                                                  AS content_stay_time,
  CAST(NULL AS INTEGER)                                                  AS content_bounce_flag,
  CAST(NULL AS VARCHAR(200))                                             AS content_exit_page,
  CAST(NULL AS VARCHAR(100))                                             AS content_session_id,
  CAST(NULL AS INTEGER)                                                  AS content_page_view_count,
  CAST(NULL AS INTEGER)                                                  AS content_unique_visitor,
  CAST(NULL AS VARCHAR(500))                                             AS content_referer_url,
  CAST(NULL AS VARCHAR(100))                                             AS content_utm_source,
  CAST(NULL AS VARCHAR(100))                                             AS content_utm_medium,
  CAST(NULL AS VARCHAR(100))                                             AS content_utm_campaign,
  CAST(NULL AS VARCHAR(50))                                              AS content_interaction_device,
  CAST(NULL AS VARCHAR(200))                                             AS content_content_title,
  CAST(NULL AS VARCHAR(50))                                              AS content_content_type,
  CAST(NULL AS VARCHAR(50))                                              AS content_content_category,
  CAST(NULL AS BIGINT)                                                   AS content_author_id,
  CAST(NULL AS VARCHAR(100))                                             AS content_author_name,
  CAST(NULL AS TIMESTAMP)                                                AS content_publish_time,
  CAST(NULL AS DATE)                                                     AS content_publish_date,
  CAST(NULL AS INTEGER)                                                  AS content_content_length,
  CAST(NULL AS INTEGER)                                                  AS content_word_count,
  CAST(NULL AS INTEGER)                                                  AS content_read_count,
  CAST(NULL AS INTEGER)                                                  AS content_content_like_count,
  CAST(NULL AS INTEGER)                                                  AS content_content_comment_count,
  CAST(NULL AS INTEGER)                                                  AS content_content_share_count,
  CAST(NULL AS INTEGER)                                                  AS content_content_collect_count,
  CAST(NULL AS INTEGER)                                                  AS content_topic_id,
  CAST(NULL AS VARCHAR(100))                                             AS content_topic_name,
  CAST(NULL AS INTEGER)                                                  AS content_is_hot,
  CAST(NULL AS INTEGER)                                                  AS content_is_recommend,
  CAST(NULL AS VARCHAR(20))                                              AS content_content_status,
  CAST(NULL AS NUMERIC(5,2))                                             AS content_content_score,
  -- ========== social_* (25) — 场景1 不适用 ==========
  CAST(NULL AS BIGINT)                                                   AS social_relation_id,
  CAST(NULL AS BIGINT)                                                   AS social_target_user_id,
  CAST(NULL AS VARCHAR(50))                                              AS social_relation_type,
  CAST(NULL AS VARCHAR(50))                                              AS social_relation_type_name,
  CAST(NULL AS INTEGER)                                                  AS social_is_mutual,
  CAST(NULL AS INTEGER)                                                  AS social_interaction_count,
  CAST(NULL AS TIMESTAMP)                                                AS social_last_interaction_time,
  CAST(NULL AS VARCHAR(20))                                              AS social_relation_status,
  CAST(NULL AS VARCHAR(50))                                              AS social_source,
  CAST(NULL AS INTEGER)                                                  AS social_group_id,
  CAST(NULL AS VARCHAR(100))                                             AS social_group_name,
  CAST(NULL AS VARCHAR(100))                                             AS social_remark,
  CAST(NULL AS INTEGER)                                                  AS social_intimacy_level,
  CAST(NULL AS INTEGER)                                                  AS social_chat_count,
  CAST(NULL AS INTEGER)                                                  AS social_call_count,
  CAST(NULL AS INTEGER)                                                  AS social_video_call_count,
  CAST(NULL AS INTEGER)                                                  AS social_gift_count,
  CAST(NULL AS INTEGER)                                                  AS social_follow_days,
  CAST(NULL AS NUMERIC(5,2))                                             AS social_interaction_frequency,
  CAST(NULL AS INTEGER)                                                  AS social_common_friends,
  CAST(NULL AS INTEGER)                                                  AS social_common_groups,
  CAST(NULL AS INTEGER)                                                  AS social_social_distance,
  CAST(NULL AS NUMERIC(5,2))                                             AS social_relationship_strength,
  CAST(NULL AS INTEGER)                                                  AS social_trust_level,
  CAST(NULL AS NUMERIC(5,2))                                             AS social_contact_importance,
  -- ========== profile_* (15) — 场景1 不适用 ==========
  CAST(NULL AS VARCHAR(500))                                             AS profile_avatar_url,
  CAST(NULL AS VARCHAR(50))                                              AS profile_profession,
  CAST(NULL AS VARCHAR(50))                                              AS profile_education,
  CAST(NULL AS VARCHAR(500))                                             AS profile_interests,
  CAST(NULL AS VARCHAR(20))                                              AS profile_active_level,
  CAST(NULL AS NUMERIC(5,2))                                             AS profile_influence_score,
  CAST(NULL AS NUMERIC(18,2))                                            AS profile_social_value,
  CAST(NULL AS VARCHAR(500))                                             AS profile_user_tags,
  CAST(NULL AS INTEGER)                                                  AS profile_fans_count,
  CAST(NULL AS INTEGER)                                                  AS profile_follow_count,
  CAST(NULL AS INTEGER)                                                  AS profile_friend_count,
  CAST(NULL AS NUMERIC(5,2))                                             AS profile_social_activity_score,
  CAST(NULL AS NUMERIC(5,2))                                             AS profile_content_creation_score,
  CAST(NULL AS NUMERIC(5,2))                                             AS profile_engagement_score,
  CAST(NULL AS INTEGER)                                                  AS profile_social_influence_rank,
  -- ========== 审计字段 (4) ==========
  'N'                                                                    AS del_flag,
  '${P_CYCLE_ID}'                                                        AS crt_cycle_id,
  '${P_CYCLE_ID}'                                                        AS last_upd_cycle_id,
  CURRENT_TIMESTAMP                                                      AS dw_last_update_date
FROM ods.ods_order_main_f oom
LEFT JOIN dim.dim_product_d dpd
  ON oom.product_id = dpd.product_id
 AND dpd.del_flag = 'N'
LEFT JOIN dim.dim_user_base_d dub
  ON oom.user_id = dub.user_id
 AND dub.del_flag = 'N'
WHERE oom.del_flag = 'N'

UNION ALL

-- =======================================================
-- 场景2: 内容互动 (oci + dcd + dub7)
-- =======================================================
SELECT
  -- ========== user_* (30) ==========
  dub7.user_id                                                           AS user_user_id,
  COALESCE(dub7.user_name, '')                                           AS user_user_name,
  CONCAT(LEFT(COALESCE(dub7.user_phone, ''), 3), '****',
         RIGHT(COALESCE(dub7.user_phone, ''), 4))                        AS user_user_phone,
  CASE dub7.gender WHEN 'M' THEN '男' WHEN 'F' THEN '女'
       ELSE '未知' END                                                   AS user_gender,
  CAST(EXTRACT(YEAR FROM CURRENT_DATE) AS INTEGER)
    - CAST(EXTRACT(YEAR FROM dub7.birthday) AS INTEGER)                  AS user_age,
  dub7.birthday                                                          AS user_birthday,
  COALESCE(dub7.province_name, '')                                       AS user_province_name,
  COALESCE(dub7.city_name, '')                                           AS user_city_name,
  COALESCE(dub7.user_level, 0)                                           AS user_user_level,
  COALESCE(dub7.user_level_name, '')                                     AS user_user_level_name,
  COALESCE(dub7.vip_status, 0)                                           AS user_vip_status,
  dub7.register_time                                                     AS user_register_time,
  CAST(dub7.register_time AS DATE)                                       AS user_register_date,
  COALESCE(dub7.user_status, '')                                         AS user_user_status,
  CASE dub7.user_status WHEN 'ACTIVE' THEN '正常' WHEN 'INACTIVE' THEN '未激活'
       WHEN 'BANNED' THEN '封禁' ELSE '未知' END                         AS user_user_status_name,
  COALESCE(dub7.source_channel, '')                                      AS user_source_channel,
  COALESCE(dub7.source_type, '')                                         AS user_source_type,
  dub7.first_active_time                                                 AS user_first_active_time,
  dub7.last_active_time                                                  AS user_last_active_time,
  COALESCE(dub7.active_days, 0)                                          AS user_active_days,
  COALESCE(dub7.total_score, 0)                                          AS user_total_score,
  COALESCE(dub7.credit_score, 0)                                         AS user_credit_score,
  COALESCE(dub7.risk_level, '')                                          AS user_risk_level,
  COALESCE(dub7.device_type, '')                                         AS user_device_type,
  COALESCE(dub7.os_type, '')                                             AS user_os_type,
  COALESCE(dub7.app_version, '')                                         AS user_app_version,
  COALESCE(dub7.ip_address, '')                                          AS user_ip_address,
  COALESCE(dub7.network_type, '')                                        AS user_network_type,
  COALESCE(dub7.is_real_name, 0)                                         AS user_is_real_name,
  COALESCE(dub7.verify_status, '')                                       AS user_verify_status,
  -- ========== behavior_* (10) ==========
  CAST(NULL AS BIGINT)                                                   AS behavior_id,
  oci.interaction_time                                                   AS behavior_time,
  CAST(oci.interaction_time AS DATE)                                     AS behavior_date,
  CAST(EXTRACT(HOUR FROM oci.interaction_time) AS INTEGER)               AS behavior_hour,
  CAST(EXTRACT(DOW FROM oci.interaction_time) + 1 AS INTEGER)            AS behavior_weekday,
  CAST(EXTRACT(MONTH FROM oci.interaction_time) AS INTEGER)              AS behavior_month,
  CAST(EXTRACT(QUARTER FROM oci.interaction_time) AS INTEGER)            AS behavior_quarter,
  CAST(EXTRACT(YEAR FROM oci.interaction_time) AS INTEGER)               AS behavior_year,
  CASE WHEN EXTRACT(DOW FROM oci.interaction_time) IN (0, 6) THEN 1 ELSE 0 END AS is_weekend,
  CASE WHEN EXTRACT(HOUR FROM oci.interaction_time) BETWEEN 0 AND 5 THEN '凌晨'
       WHEN EXTRACT(HOUR FROM oci.interaction_time) BETWEEN 6 AND 11 THEN '上午'
       WHEN EXTRACT(HOUR FROM oci.interaction_time) BETWEEN 12 AND 13 THEN '中午'
       WHEN EXTRACT(HOUR FROM oci.interaction_time) BETWEEN 14 AND 17 THEN '下午'
       ELSE '晚上' END                                                   AS time_period,
  -- ========== order_* (30) — 场景2 不适用 ==========
  CAST(NULL AS BIGINT)                                                   AS order_order_id,
  CAST(NULL AS VARCHAR(50))                                              AS order_order_no,
  CAST(NULL AS VARCHAR(20))                                              AS order_order_status,
  CAST(NULL AS VARCHAR(50))                                              AS order_order_status_name,
  CAST(NULL AS NUMERIC(18,2))                                            AS order_order_amount,
  CAST(NULL AS NUMERIC(18,2))                                            AS order_discount_amount,
  CAST(NULL AS NUMERIC(18,2))                                            AS order_actual_amount,
  CAST(NULL AS VARCHAR(50))                                              AS order_payment_method,
  CAST(NULL AS TIMESTAMP)                                                AS order_payment_time,
  CAST(NULL AS NUMERIC(18,2))                                            AS order_shipping_fee,
  CAST(NULL AS INTEGER)                                                  AS order_product_count,
  CAST(NULL AS INTEGER)                                                  AS order_sku_count,
  CAST(NULL AS INTEGER)                                                  AS order_is_first_order,
  CAST(NULL AS INTEGER)                                                  AS order_coupon_id,
  CAST(NULL AS VARCHAR(100))                                             AS order_coupon_name,
  CAST(NULL AS INTEGER)                                                  AS order_points_used,
  CAST(NULL AS INTEGER)                                                  AS order_points_earned,
  CAST(NULL AS TIMESTAMP)                                                AS order_complete_time,
  CAST(NULL AS TIMESTAMP)                                                AS order_cancel_time,
  CAST(NULL AS VARCHAR(200))                                             AS order_cancel_reason,
  CAST(NULL AS INTEGER)                                                  AS order_merchant_id,
  CAST(NULL AS VARCHAR(200))                                             AS order_merchant_name,
  CAST(NULL AS VARCHAR(50))                                              AS order_delivery_type,
  CAST(NULL AS TIMESTAMP)                                                AS order_delivery_time,
  CAST(NULL AS TIMESTAMP)                                                AS order_receive_time,
  CAST(NULL AS VARCHAR(20))                                              AS order_receive_status,
  CAST(NULL AS VARCHAR(50))                                              AS order_order_source,
  CAST(NULL AS VARCHAR(500))                                             AS order_remark,
  CAST(NULL AS VARCHAR(20))                                              AS order_invoice_type,
  CAST(NULL AS VARCHAR(200))                                             AS order_invoice_title,
  -- ========== prod_* (20) — 场景2 不适用 ==========
  CAST(NULL AS BIGINT)                                                   AS prod_product_id,
  CAST(NULL AS VARCHAR(200))                                             AS prod_product_name,
  CAST(NULL AS VARCHAR(50))                                              AS prod_product_code,
  CAST(NULL AS BIGINT)                                                   AS prod_sku_id,
  CAST(NULL AS VARCHAR(200))                                             AS prod_sku_name,
  CAST(NULL AS INTEGER)                                                  AS prod_brand_id,
  CAST(NULL AS VARCHAR(100))                                             AS prod_brand_name,
  CAST(NULL AS INTEGER)                                                  AS prod_category_id,
  CAST(NULL AS VARCHAR(100))                                             AS prod_category_name,
  CAST(NULL AS VARCHAR(100))                                             AS prod_category_level1,
  CAST(NULL AS VARCHAR(100))                                             AS prod_category_level2,
  CAST(NULL AS VARCHAR(100))                                             AS prod_category_level3,
  CAST(NULL AS NUMERIC(18,2))                                            AS prod_price,
  CAST(NULL AS NUMERIC(18,2))                                            AS prod_cost_price,
  CAST(NULL AS NUMERIC(5,2))                                             AS prod_profit_rate,
  CAST(NULL AS VARCHAR(20))                                              AS prod_stock_status,
  CAST(NULL AS VARCHAR(20))                                              AS prod_sale_status,
  CAST(NULL AS VARCHAR(50))                                              AS prod_product_type,
  CAST(NULL AS INTEGER)                                                  AS prod_is_virtual,
  CAST(NULL AS INTEGER)                                                  AS prod_supplier_id,
  -- ========== content_* (50) ==========
  oci.interaction_id                                                     AS content_interaction_id,
  oci.content_id                                                         AS content_content_id,
  oci.interaction_type                                                   AS content_interaction_type,
  CASE oci.interaction_type WHEN 'VIEW' THEN '浏览' WHEN 'LIKE' THEN '点赞'
       WHEN 'COMMENT' THEN '评论' WHEN 'SHARE' THEN '分享'
       WHEN 'COLLECT' THEN '收藏' ELSE '其他' END                        AS content_interaction_type_name,
  oci.duration_seconds                                                   AS content_duration_seconds,
  oci.duration_seconds / 60.0                                            AS content_duration_minutes,
  oci.comment_content                                                    AS content_comment_content,
  LENGTH(oci.comment_content)                                            AS content_comment_word_count,
  oci.share_platform                                                     AS content_share_platform,
  oci.share_count                                                        AS content_share_count,
  oci.like_count                                                         AS content_like_count,
  oci.comment_count                                                      AS content_comment_count,
  oci.collect_count                                                      AS content_collect_count,
  oci.forward_count                                                      AS content_forward_count,
  oci.is_original                                                        AS content_is_original,
  oci.source_type                                                        AS content_source_type,
  oci.browse_depth                                                       AS content_browse_depth,
  oci.scroll_percentage                                                  AS content_scroll_percentage,
  oci.click_count                                                        AS content_click_count,
  oci.stay_time                                                          AS content_stay_time,
  oci.bounce_flag                                                        AS content_bounce_flag,
  oci.exit_page                                                          AS content_exit_page,
  oci.session_id                                                         AS content_session_id,
  oci.page_view_count                                                    AS content_page_view_count,
  oci.unique_visitor                                                     AS content_unique_visitor,
  oci.referer_url                                                        AS content_referer_url,
  oci.utm_source                                                         AS content_utm_source,
  oci.utm_medium                                                         AS content_utm_medium,
  oci.utm_campaign                                                       AS content_utm_campaign,
  oci.interaction_device                                                 AS content_interaction_device,
  COALESCE(dcd.content_title, '')                                        AS content_content_title,
  COALESCE(dcd.content_type, '')                                         AS content_content_type,
  COALESCE(dcd.content_category, '')                                     AS content_content_category,
  dcd.author_id                                                          AS content_author_id,
  COALESCE(dcd.author_name, '')                                          AS content_author_name,
  dcd.publish_time                                                       AS content_publish_time,
  CAST(dcd.publish_time AS DATE)                                         AS content_publish_date,
  COALESCE(dcd.content_length, 0)                                        AS content_content_length,
  COALESCE(dcd.word_count, 0)                                            AS content_word_count,
  COALESCE(dcd.read_count, 0)                                            AS content_read_count,
  COALESCE(dcd.content_like_count, 0)                                    AS content_content_like_count,
  COALESCE(dcd.content_comment_count, 0)                                 AS content_content_comment_count,
  COALESCE(dcd.content_share_count, 0)                                   AS content_content_share_count,
  COALESCE(dcd.content_collect_count, 0)                                 AS content_content_collect_count,
  COALESCE(dcd.topic_id, 0)                                              AS content_topic_id,
  COALESCE(dcd.topic_name, '')                                           AS content_topic_name,
  COALESCE(dcd.is_hot, 0)                                                AS content_is_hot,
  COALESCE(dcd.is_recommend, 0)                                          AS content_is_recommend,
  COALESCE(dcd.content_status, '')                                       AS content_content_status,
  COALESCE(dcd.content_score, 0)                                         AS content_content_score,
  -- ========== social_* (25) — 场景2 不适用 ==========
  CAST(NULL AS BIGINT)                                                   AS social_relation_id,
  CAST(NULL AS BIGINT)                                                   AS social_target_user_id,
  CAST(NULL AS VARCHAR(50))                                              AS social_relation_type,
  CAST(NULL AS VARCHAR(50))                                              AS social_relation_type_name,
  CAST(NULL AS INTEGER)                                                  AS social_is_mutual,
  CAST(NULL AS INTEGER)                                                  AS social_interaction_count,
  CAST(NULL AS TIMESTAMP)                                                AS social_last_interaction_time,
  CAST(NULL AS VARCHAR(20))                                              AS social_relation_status,
  CAST(NULL AS VARCHAR(50))                                              AS social_source,
  CAST(NULL AS INTEGER)                                                  AS social_group_id,
  CAST(NULL AS VARCHAR(100))                                             AS social_group_name,
  CAST(NULL AS VARCHAR(100))                                             AS social_remark,
  CAST(NULL AS INTEGER)                                                  AS social_intimacy_level,
  CAST(NULL AS INTEGER)                                                  AS social_chat_count,
  CAST(NULL AS INTEGER)                                                  AS social_call_count,
  CAST(NULL AS INTEGER)                                                  AS social_video_call_count,
  CAST(NULL AS INTEGER)                                                  AS social_gift_count,
  CAST(NULL AS INTEGER)                                                  AS social_follow_days,
  CAST(NULL AS NUMERIC(5,2))                                             AS social_interaction_frequency,
  CAST(NULL AS INTEGER)                                                  AS social_common_friends,
  CAST(NULL AS INTEGER)                                                  AS social_common_groups,
  CAST(NULL AS INTEGER)                                                  AS social_social_distance,
  CAST(NULL AS NUMERIC(5,2))                                             AS social_relationship_strength,
  CAST(NULL AS INTEGER)                                                  AS social_trust_level,
  CAST(NULL AS NUMERIC(5,2))                                             AS social_contact_importance,
  -- ========== profile_* (15) — 场景2 不适用 ==========
  CAST(NULL AS VARCHAR(500))                                             AS profile_avatar_url,
  CAST(NULL AS VARCHAR(50))                                              AS profile_profession,
  CAST(NULL AS VARCHAR(50))                                              AS profile_education,
  CAST(NULL AS VARCHAR(500))                                             AS profile_interests,
  CAST(NULL AS VARCHAR(20))                                              AS profile_active_level,
  CAST(NULL AS NUMERIC(5,2))                                             AS profile_influence_score,
  CAST(NULL AS NUMERIC(18,2))                                            AS profile_social_value,
  CAST(NULL AS VARCHAR(500))                                             AS profile_user_tags,
  CAST(NULL AS INTEGER)                                                  AS profile_fans_count,
  CAST(NULL AS INTEGER)                                                  AS profile_follow_count,
  CAST(NULL AS INTEGER)                                                  AS profile_friend_count,
  CAST(NULL AS NUMERIC(5,2))                                             AS profile_social_activity_score,
  CAST(NULL AS NUMERIC(5,2))                                             AS profile_content_creation_score,
  CAST(NULL AS NUMERIC(5,2))                                             AS profile_engagement_score,
  CAST(NULL AS INTEGER)                                                  AS profile_social_influence_rank,
  -- ========== 审计字段 (4) ==========
  'N'                                                                    AS del_flag,
  '${P_CYCLE_ID}'                                                        AS crt_cycle_id,
  '${P_CYCLE_ID}'                                                        AS last_upd_cycle_id,
  CURRENT_TIMESTAMP                                                      AS dw_last_update_date
FROM ods.ods_content_interaction_f oci
LEFT JOIN dim.dim_content_d dcd
  ON oci.content_id = dcd.content_id
 AND dcd.del_flag = 'N'
LEFT JOIN dim.dim_user_base_d dub7
  ON oci.user_id = dub7.user_id
 AND dub7.del_flag = 'N'
WHERE oci.del_flag = 'N'

UNION ALL

-- =======================================================
-- 场景3: 社交关系 (osr + dup + dub10)
-- =======================================================
SELECT
  -- ========== user_* (30) ==========
  dub10.user_id                                                          AS user_user_id,
  COALESCE(dub10.user_name, '')                                          AS user_user_name,
  CONCAT(LEFT(COALESCE(dub10.user_phone, ''), 3), '****',
         RIGHT(COALESCE(dub10.user_phone, ''), 4))                       AS user_user_phone,
  CASE dub10.gender WHEN 'M' THEN '男' WHEN 'F' THEN '女'
       ELSE '未知' END                                                   AS user_gender,
  CAST(EXTRACT(YEAR FROM CURRENT_DATE) AS INTEGER)
    - CAST(EXTRACT(YEAR FROM dub10.birthday) AS INTEGER)                 AS user_age,
  dub10.birthday                                                         AS user_birthday,
  COALESCE(dub10.province_name, '')                                      AS user_province_name,
  COALESCE(dub10.city_name, '')                                          AS user_city_name,
  COALESCE(dub10.user_level, 0)                                          AS user_user_level,
  COALESCE(dub10.user_level_name, '')                                    AS user_user_level_name,
  COALESCE(dub10.vip_status, 0)                                          AS user_vip_status,
  dub10.register_time                                                    AS user_register_time,
  CAST(dub10.register_time AS DATE)                                      AS user_register_date,
  COALESCE(dub10.user_status, '')                                        AS user_user_status,
  CASE dub10.user_status WHEN 'ACTIVE' THEN '正常' WHEN 'INACTIVE' THEN '未激活'
       WHEN 'BANNED' THEN '封禁' ELSE '未知' END                         AS user_user_status_name,
  COALESCE(dub10.source_channel, '')                                     AS user_source_channel,
  COALESCE(dub10.source_type, '')                                        AS user_source_type,
  dub10.first_active_time                                                AS user_first_active_time,
  dub10.last_active_time                                                 AS user_last_active_time,
  COALESCE(dub10.active_days, 0)                                         AS user_active_days,
  COALESCE(dub10.total_score, 0)                                         AS user_total_score,
  COALESCE(dub10.credit_score, 0)                                        AS user_credit_score,
  COALESCE(dub10.risk_level, '')                                         AS user_risk_level,
  COALESCE(dub10.device_type, '')                                        AS user_device_type,
  COALESCE(dub10.os_type, '')                                            AS user_os_type,
  COALESCE(dub10.app_version, '')                                        AS user_app_version,
  COALESCE(dub10.ip_address, '')                                         AS user_ip_address,
  COALESCE(dub10.network_type, '')                                       AS user_network_type,
  COALESCE(dub10.is_real_name, 0)                                        AS user_is_real_name,
  COALESCE(dub10.verify_status, '')                                      AS user_verify_status,
  -- ========== behavior_* (10) ==========
  osr.behavior_id                                                        AS behavior_id,
  osr.create_time                                                        AS behavior_time,
  CAST(osr.create_time AS DATE)                                          AS behavior_date,
  CAST(EXTRACT(HOUR FROM osr.create_time) AS INTEGER)                    AS behavior_hour,
  CAST(EXTRACT(DOW FROM osr.create_time) + 1 AS INTEGER)                 AS behavior_weekday,
  CAST(EXTRACT(MONTH FROM osr.create_time) AS INTEGER)                   AS behavior_month,
  CAST(EXTRACT(QUARTER FROM osr.create_time) AS INTEGER)                 AS behavior_quarter,
  CAST(EXTRACT(YEAR FROM osr.create_time) AS INTEGER)                    AS behavior_year,
  CASE WHEN EXTRACT(DOW FROM osr.create_time) IN (0, 6) THEN 1 ELSE 0 END AS is_weekend,
  CASE WHEN EXTRACT(HOUR FROM osr.create_time) BETWEEN 0 AND 5 THEN '凌晨'
       WHEN EXTRACT(HOUR FROM osr.create_time) BETWEEN 6 AND 11 THEN '上午'
       WHEN EXTRACT(HOUR FROM osr.create_time) BETWEEN 12 AND 13 THEN '中午'
       WHEN EXTRACT(HOUR FROM osr.create_time) BETWEEN 14 AND 17 THEN '下午'
       ELSE '晚上' END                                                   AS time_period,
  -- ========== order_* (30) — 场景3 不适用 ==========
  CAST(NULL AS BIGINT)                                                   AS order_order_id,
  CAST(NULL AS VARCHAR(50))                                              AS order_order_no,
  CAST(NULL AS VARCHAR(20))                                              AS order_order_status,
  CAST(NULL AS VARCHAR(50))                                              AS order_order_status_name,
  CAST(NULL AS NUMERIC(18,2))                                            AS order_order_amount,
  CAST(NULL AS NUMERIC(18,2))                                            AS order_discount_amount,
  CAST(NULL AS NUMERIC(18,2))                                            AS order_actual_amount,
  CAST(NULL AS VARCHAR(50))                                              AS order_payment_method,
  CAST(NULL AS TIMESTAMP)                                                AS order_payment_time,
  CAST(NULL AS NUMERIC(18,2))                                            AS order_shipping_fee,
  CAST(NULL AS INTEGER)                                                  AS order_product_count,
  CAST(NULL AS INTEGER)                                                  AS order_sku_count,
  CAST(NULL AS INTEGER)                                                  AS order_is_first_order,
  CAST(NULL AS INTEGER)                                                  AS order_coupon_id,
  CAST(NULL AS VARCHAR(100))                                             AS order_coupon_name,
  CAST(NULL AS INTEGER)                                                  AS order_points_used,
  CAST(NULL AS INTEGER)                                                  AS order_points_earned,
  CAST(NULL AS TIMESTAMP)                                                AS order_complete_time,
  CAST(NULL AS TIMESTAMP)                                                AS order_cancel_time,
  CAST(NULL AS VARCHAR(200))                                             AS order_cancel_reason,
  CAST(NULL AS INTEGER)                                                  AS order_merchant_id,
  CAST(NULL AS VARCHAR(200))                                             AS order_merchant_name,
  CAST(NULL AS VARCHAR(50))                                              AS order_delivery_type,
  CAST(NULL AS TIMESTAMP)                                                AS order_delivery_time,
  CAST(NULL AS TIMESTAMP)                                                AS order_receive_time,
  CAST(NULL AS VARCHAR(20))                                              AS order_receive_status,
  CAST(NULL AS VARCHAR(50))                                              AS order_order_source,
  CAST(NULL AS VARCHAR(500))                                             AS order_remark,
  CAST(NULL AS VARCHAR(20))                                              AS order_invoice_type,
  CAST(NULL AS VARCHAR(200))                                             AS order_invoice_title,
  -- ========== prod_* (20) — 场景3 不适用 ==========
  CAST(NULL AS BIGINT)                                                   AS prod_product_id,
  CAST(NULL AS VARCHAR(200))                                             AS prod_product_name,
  CAST(NULL AS VARCHAR(50))                                              AS prod_product_code,
  CAST(NULL AS BIGINT)                                                   AS prod_sku_id,
  CAST(NULL AS VARCHAR(200))                                             AS prod_sku_name,
  CAST(NULL AS INTEGER)                                                  AS prod_brand_id,
  CAST(NULL AS VARCHAR(100))                                             AS prod_brand_name,
  CAST(NULL AS INTEGER)                                                  AS prod_category_id,
  CAST(NULL AS VARCHAR(100))                                             AS prod_category_name,
  CAST(NULL AS VARCHAR(100))                                             AS prod_category_level1,
  CAST(NULL AS VARCHAR(100))                                             AS prod_category_level2,
  CAST(NULL AS VARCHAR(100))                                             AS prod_category_level3,
  CAST(NULL AS NUMERIC(18,2))                                            AS prod_price,
  CAST(NULL AS NUMERIC(18,2))                                            AS prod_cost_price,
  CAST(NULL AS NUMERIC(5,2))                                             AS prod_profit_rate,
  CAST(NULL AS VARCHAR(20))                                              AS prod_stock_status,
  CAST(NULL AS VARCHAR(20))                                              AS prod_sale_status,
  CAST(NULL AS VARCHAR(50))                                              AS prod_product_type,
  CAST(NULL AS INTEGER)                                                  AS prod_is_virtual,
  CAST(NULL AS INTEGER)                                                  AS prod_supplier_id,
  -- ========== content_* (50) — 场景3 不适用 ==========
  CAST(NULL AS BIGINT)                                                   AS content_interaction_id,
  CAST(NULL AS BIGINT)                                                   AS content_content_id,
  CAST(NULL AS VARCHAR(50))                                              AS content_interaction_type,
  CAST(NULL AS VARCHAR(50))                                              AS content_interaction_type_name,
  CAST(NULL AS INTEGER)                                                  AS content_duration_seconds,
  CAST(NULL AS NUMERIC(5,2))                                             AS content_duration_minutes,
  CAST(NULL AS VARCHAR(1000))                                            AS content_comment_content,
  CAST(NULL AS INTEGER)                                                  AS content_comment_word_count,
  CAST(NULL AS VARCHAR(50))                                              AS content_share_platform,
  CAST(NULL AS INTEGER)                                                  AS content_share_count,
  CAST(NULL AS INTEGER)                                                  AS content_like_count,
  CAST(NULL AS INTEGER)                                                  AS content_comment_count,
  CAST(NULL AS INTEGER)                                                  AS content_collect_count,
  CAST(NULL AS INTEGER)                                                  AS content_forward_count,
  CAST(NULL AS INTEGER)                                                  AS content_is_original,
  CAST(NULL AS VARCHAR(50))                                              AS content_source_type,
  CAST(NULL AS INTEGER)                                                  AS content_browse_depth,
  CAST(NULL AS NUMERIC(5,2))                                             AS content_scroll_percentage,
  CAST(NULL AS INTEGER)                                                  AS content_click_count,
  CAST(NULL AS INTEGER)                                                  AS content_stay_time,
  CAST(NULL AS INTEGER)                                                  AS content_bounce_flag,
  CAST(NULL AS VARCHAR(200))                                             AS content_exit_page,
  CAST(NULL AS VARCHAR(100))                                             AS content_session_id,
  CAST(NULL AS INTEGER)                                                  AS content_page_view_count,
  CAST(NULL AS INTEGER)                                                  AS content_unique_visitor,
  CAST(NULL AS VARCHAR(500))                                             AS content_referer_url,
  CAST(NULL AS VARCHAR(100))                                             AS content_utm_source,
  CAST(NULL AS VARCHAR(100))                                             AS content_utm_medium,
  CAST(NULL AS VARCHAR(100))                                             AS content_utm_campaign,
  CAST(NULL AS VARCHAR(50))                                              AS content_interaction_device,
  CAST(NULL AS VARCHAR(200))                                             AS content_content_title,
  CAST(NULL AS VARCHAR(50))                                              AS content_content_type,
  CAST(NULL AS VARCHAR(50))                                              AS content_content_category,
  CAST(NULL AS BIGINT)                                                   AS content_author_id,
  CAST(NULL AS VARCHAR(100))                                             AS content_author_name,
  CAST(NULL AS TIMESTAMP)                                                AS content_publish_time,
  CAST(NULL AS DATE)                                                     AS content_publish_date,
  CAST(NULL AS INTEGER)                                                  AS content_content_length,
  CAST(NULL AS INTEGER)                                                  AS content_word_count,
  CAST(NULL AS INTEGER)                                                  AS content_read_count,
  CAST(NULL AS INTEGER)                                                  AS content_content_like_count,
  CAST(NULL AS INTEGER)                                                  AS content_content_comment_count,
  CAST(NULL AS INTEGER)                                                  AS content_content_share_count,
  CAST(NULL AS INTEGER)                                                  AS content_content_collect_count,
  CAST(NULL AS INTEGER)                                                  AS content_topic_id,
  CAST(NULL AS VARCHAR(100))                                             AS content_topic_name,
  CAST(NULL AS INTEGER)                                                  AS content_is_hot,
  CAST(NULL AS INTEGER)                                                  AS content_is_recommend,
  CAST(NULL AS VARCHAR(20))                                              AS content_content_status,
  CAST(NULL AS NUMERIC(5,2))                                             AS content_content_score,
  -- ========== social_* (25) ==========
  osr.relation_id                                                        AS social_relation_id,
  osr.target_user_id                                                     AS social_target_user_id,
  osr.relation_type                                                      AS social_relation_type,
  CASE osr.relation_type WHEN 'FOLLOW' THEN '关注' WHEN 'FRIEND' THEN '好友'
       WHEN 'BLOCK' THEN '屏蔽' WHEN 'BLACKLIST' THEN '黑名单'
       ELSE '其他' END                                                   AS social_relation_type_name,
  osr.is_mutual                                                          AS social_is_mutual,
  osr.interaction_count                                                  AS social_interaction_count,
  osr.last_interaction_time                                              AS social_last_interaction_time,
  osr.relation_status                                                    AS social_relation_status,
  osr.source                                                             AS social_source,
  osr.group_id                                                           AS social_group_id,
  osr.group_name                                                         AS social_group_name,
  osr.remark                                                             AS social_remark,
  osr.intimacy_level                                                     AS social_intimacy_level,
  osr.chat_count                                                         AS social_chat_count,
  osr.call_count                                                         AS social_call_count,
  osr.video_call_count                                                   AS social_video_call_count,
  osr.gift_count                                                         AS social_gift_count,
  osr.follow_days                                                        AS social_follow_days,
  osr.interaction_frequency                                              AS social_interaction_frequency,
  osr.common_friends                                                     AS social_common_friends,
  osr.common_groups                                                      AS social_common_groups,
  osr.social_distance                                                    AS social_social_distance,
  osr.relationship_strength                                              AS social_relationship_strength,
  osr.trust_level                                                        AS social_trust_level,
  osr.contact_importance                                                 AS social_contact_importance,
  -- ========== profile_* (15) ==========
  COALESCE(dup.avatar_url, '')                                           AS profile_avatar_url,
  COALESCE(dup.profession, '')                                           AS profile_profession,
  COALESCE(dup.education, '')                                            AS profile_education,
  COALESCE(dup.interests, '')                                            AS profile_interests,
  COALESCE(dup.active_level, '')                                         AS profile_active_level,
  COALESCE(dup.influence_score, 0)                                       AS profile_influence_score,
  COALESCE(dup.social_value, 0)                                          AS profile_social_value,
  COALESCE(dup.user_tags, '')                                            AS profile_user_tags,
  COALESCE(dup.fans_count, 0)                                            AS profile_fans_count,
  COALESCE(dup.follow_count, 0)                                          AS profile_follow_count,
  COALESCE(dup.friend_count, 0)                                          AS profile_friend_count,
  COALESCE(dup.social_activity_score, 0)                                 AS profile_social_activity_score,
  COALESCE(dup.content_creation_score, 0)                                AS profile_content_creation_score,
  COALESCE(dup.engagement_score, 0)                                      AS profile_engagement_score,
  COALESCE(dup.social_influence_rank, 0)                                 AS profile_social_influence_rank,
  -- ========== 审计字段 (4) ==========
  'N'                                                                    AS del_flag,
  '${P_CYCLE_ID}'                                                        AS crt_cycle_id,
  '${P_CYCLE_ID}'                                                        AS last_upd_cycle_id,
  CURRENT_TIMESTAMP                                                      AS dw_last_update_date
FROM ods.ods_social_relation_f osr
LEFT JOIN dim.dim_user_profile_d dup
  ON osr.user_id = dup.user_id
 AND dup.del_flag = 'N'
LEFT JOIN dim.dim_user_base_d dub10
  ON osr.user_id = dub10.user_id
 AND dub10.del_flag = 'N'
WHERE osr.del_flag = 'N'
;
